apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: demo-role
  namespace: kafka
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - deployments
      - replicasets
      - configmaps
      - secrets
      - persistentvolumeclaims
      - endpoints
      - events
      - ingresses
    verbs:
      - get
      - list
      - create
      - update
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: demo-role-binding
  namespace: kafka
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: demo-role
subjects:
  - namespace: default
    kind: ServiceAccount
    name: demo-user